name = "SparseArraysCOO"
uuid = "610335e3-e389-450b-99eb-3a0a1c8c6bf9"
authors = ["Erik Schnetter <schnetter@gmail.com>"]
version = "1.0.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
